'use client';

import * as React from 'react';
import { useDocument } from '../../hooks/useDocument';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Download, FileText } from 'lucide-react';
import Link from 'next/link';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { SnapshotViewer } from './SnapshotViewer';

export function DocumentDetails({ documentId }: { documentId: string }) {
  const { useGeneratedDocument } = useDocument();
  const { data: doc, isLoading } = useGeneratedDocument(documentId);

  if (isLoading) return <div className="p-8 text-center">Loading document...</div>;
  if (!doc) return <div className="p-8 text-center">Document not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/hr/documents">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div className="flex-1">
          <h2 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <FileText className="h-6 w-6 text-primary" />
            Document: {doc.id.split('-')[0]}
          </h2>
          <p className="text-muted-foreground">Type ID: {doc.documentTypeId}</p>
        </div>
        
        <div className="flex items-center gap-2">
          <Badge variant={doc.status === 'GENERATED' || doc.status === 'SIGNED' ? 'default' : 'secondary'} className="text-sm px-3 py-1">
            {doc.status}
          </Badge>

          <Button variant="outline" size="sm" onClick={() => alert('Backend API for download missing.')}>
            <Download className="mr-2 h-4 w-4" /> Download PDF
          </Button>
        </div>
      </div>

      <Tabs defaultValue="metadata" className="w-full">
        <TabsList className="w-full justify-start border-b rounded-none h-auto p-0 bg-transparent">
          <TabsTrigger value="metadata" className="data-[state=active]:border-b-2 rounded-none data-[state=active]:border-primary px-6 py-3">Metadata</TabsTrigger>
          <TabsTrigger value="snapshot" className="data-[state=active]:border-b-2 rounded-none data-[state=active]:border-primary px-6 py-3">Snapshot Payload</TabsTrigger>
          <TabsTrigger value="history" className="data-[state=active]:border-b-2 rounded-none data-[state=active]:border-primary px-6 py-3">History</TabsTrigger>
        </TabsList>
        
        <div className="pt-6">
          <TabsContent value="metadata">
            <div className="grid gap-6 md:grid-cols-2">
              <Card>
                <CardHeader>
                  <CardTitle>Generation Information</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-muted-foreground">Template ID</p>
                      <p className="font-medium text-xs break-all">{doc.templateId}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Version ID</p>
                      <p className="font-medium text-xs break-all">{doc.templateVersionId}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Generated By</p>
                      <p className="font-medium">{doc.generatedBy}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Generated Date</p>
                      <p className="font-medium">{new Date(doc.createdAt).toLocaleString()}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Related Entities</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex justify-between items-center border-b pb-2">
                    <span className="text-sm">Profile</span>
                    <span className="font-mono text-xs">{doc.profileId}</span>
                  </div>
                  {doc.candidateId && (
                    <div className="flex justify-between items-center border-b pb-2">
                      <span className="text-sm">Candidate</span>
                      <Link href={`/hr/candidates/${doc.candidateId}`} className="text-primary hover:underline text-sm font-medium">
                        View Reference
                      </Link>
                    </div>
                  )}
                  {doc.employeeId && (
                    <div className="flex justify-between items-center border-b pb-2">
                      <span className="text-sm">Employee</span>
                      <Link href={`/hr/employees/${doc.employeeId}`} className="text-primary hover:underline text-sm font-medium">
                        View Reference
                      </Link>
                    </div>
                  )}
                  {doc.workflowInstanceId && (
                    <div className="flex justify-between items-center border-b pb-2">
                      <span className="text-sm">Workflow</span>
                      <Link href={`/hr/workflows/${doc.workflowInstanceId}`} className="text-primary hover:underline text-sm font-medium">
                        View Execution
                      </Link>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          
          <TabsContent value="snapshot">
            <SnapshotViewer snapshotData={doc.snapshots?.[0]} />
          </TabsContent>

          <TabsContent value="history">
            <Card>
              <CardContent className="flex flex-col items-center justify-center p-12 text-center">
                <div className="h-12 w-12 rounded-full bg-muted flex items-center justify-center mb-4">
                  <span className="text-muted-foreground text-xl">📜</span>
                </div>
                <h3 className="text-lg font-medium">History Unavailable</h3>
                <p className="text-muted-foreground max-w-sm mt-2">
                  The backend API currently does not support document history tracking. This section will be activated once the endpoint is available.
                </p>
              </CardContent>
            </Card>
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
}
