import { ICommand, IEvent } from '../../kernel/cqrs/cqrs.contracts';
import { AggregateRoot } from '../../kernel/domain/AggregateRoot';

/**
 * Utilities to test Domain Events and Commands synchronously.
 */
export class CqrsTestHelper {
  /**
   * Asserts that a specific event was generated by an aggregate during mutation.
   */
  static assertEventPublished<TEvent extends IEvent>(
    aggregate: AggregateRoot<any>,
    eventType: new (...args: any[]) => TEvent,
  ): TEvent {
    const events = aggregate.domainEvents;
    const event = events.find((e: any) => e instanceof eventType);
    if (!event) {
      throw new Error(
        `Expected event ${eventType.name} was not published by the aggregate.`,
      );
    }
    return event as unknown as TEvent;
  }

  /**
   * Clears event logs explicitly (useful between test runs on the same instance)
   */
  static clearEvents(aggregate: AggregateRoot<any>): void {
    aggregate.clearEvents();
  }
}
